[package]
name = "car-listing"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0"          # or whatever the latest near-sdk version is
borsh = "0.9.4"
serde = { version = "1.0", features = ["derive"] }
